
stages:         
  - build
  - test
  - deploy

build-job:       
  stage: build
  script:
   # - cd /home/build
    - git reset --hard
    - git clean -f 
    - git pull
    - npm install
    - npm run build

unit-test-job:   
  stage: test    
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - sleep 60
    - echo "Code coverage is 90%"

lint-test-job:   
  stage: test    
  script:
    - echo "Linting code... This will take about 10 seconds."
    - sleep 10
    - echo "No lint issues found."

deploy-job:      
  stage: deploy  
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
